name: CI/CD Pipeline

on:
  push:
    paths:
      - 'fullstack-web-app/**'
  pull_request:
    paths:
      - 'fullstack-web-app/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build backend Docker image
        run: docker build -t backend ./fullstack-web-app/backend

      - name: Build frontend Docker image
        run: docker build -t frontend ./fullstack-web-app/frontend

      - name: Build database Docker image
        run: docker build -t database ./fullstack-web-app/database

      - name: Run tests
        run: docker-compose run backend npm test